# ClickUp Configuration
clickup:
  api_key: "pk_xxx"
  team_id: "xxx"

# Neo4j Database Configuration  
neo4j:
  uri: "neo4j+s://xxx.databases.neo4j.io"
  username: "xxx"
  password: "xxx"

# Discord Bot Configuration
discord:
  token: "your_discord_bot_token_here"

# Webhook Server Configuration
webhooks:
  enabled: true
  host: "0.0.0.0"  # Host to bind webhook server
  port: 8000       # Port for webhook server
  public_url: "https://your-domain.com"  # Public URL for ClickUp webhooks
  
  # ngrok Configuration
  ngrok:
    enabled: true
    authtoken: "xxxxx"
    region: "us"  # us, eu, ap, au, sa, jp, in
    inspect: true  # Enable ngrok web interface
    log_level: "info"
 
 
 